Vlr1 =int(input("ingrese primer numero"))
Vlr2 =int(input("ingrese segundo numero"))
Vlr3 =int(input("ingrese tercer numero"))
suma = int(Vlr1) + int(Vlr2) + int(Vlr3)
resta = int(Vlr1) - int(Vlr2) - int(Vlr3)
multi = int(Vlr1) * int(Vlr2) * int(Vlr3)
print("La suma es:.{}".format(suma))
print("La resta es:.{}".format(resta))
print("La multiplicacion es:.{}".format(multi))
